FROM jess/transmission

RUN mkdir -p /transmission/download \
	&& mkdir -p /transmission/watch \
	&& mkdir -p /transmission/incomplete\
	&& mkdir -p /transmission/config

VOLUME ["/transmission/download"]